### ISSUE TITLE
Missing license document

### ISSUE THREAD

**Issue by akien-mga** [magogware/godot-audiostreampd#1]
Hello,

I was reviewing your submission to the Godot Asset Library but I can't find the GPLv3 license text in this repo to match what was defined on the Asset Library: https://godotengine.org/asset-library/asset/edit/5411

As a side note, I would also suggest adding a README with more details and notably a link to your GDNative source code for people who would want to build it from source: https://github.com/magogware/godot-pdstream

**Comment by magogware** [comment]
Done and done! README added (one for the pdstream repo will be coming soon with build instructions), and a licence is added. More documentation is one the way but the example project should suffice for the moment.
